### ISSUE TITLE
Annotations/QueryCount.php

### ISSUE THREAD

**Issue by alexisLefebvre** [alexislefebvre/LiipFunctionalTestBundle#1]
This file is not covered by test, despite the corresponding parameter is defined: https://github.com/alexislefebvre/LiipFunctionalTestBundle/blob/39d450b883e11c76defd5b67bcab5182dc75ae8d/Tests/App/config.yml#L31

**Comment by alexislefebvre** [comment]
See https://github.com/liip/LiipFunctionalTestBundle/issues/207.
