### ISSUE TITLE
Launch tests on MySQL on Travis CI

### ISSUE THREAD

**Issue by alexisLefebvre** [alexislefebvre/LiipFunctionalTestBundle#14]
Use only the current up-to-date LTS version.

**Comment by alexislefebvre** [comment]
That's too complicated: https://github.com/liip/LiipFunctionalTestBundle#non-sqlite

**Comment by alexisLefebvre** [comment]
That's too complicated: https://github.com/liip/LiipFunctionalTestBundle#non-sqlite
