### ISSUE TITLE
Tests more methods

### ISSUE THREAD

**Issue by alexisLefebvre** [alexislefebvre/LiipFunctionalTestBundle#4]
`isSuccessful()`

Examples:
- `fetchContent()`

See: https://github.com/liip/LiipFunctionalTestBundle/tree/master/ExampleTests

**Comment by alexislefebvre** [comment]
Fixed in https://github.com/alexislefebvre/LiipFunctionalTestBundle/commit/86d005cd1256cd85cb6d5daf6140d30fe7ccaf6b.

**Comment by alexisLefebvre** [comment]
Fixed in https://github.com/alexislefebvre/LiipFunctionalTestBundle/commit/8a337da9fd552709709d99985c14c814e29dd6c9
